### ISSUE TITLE
Undefined symbol `FT_Get_Transform` from libharfbuzz

### ISSUE THREAD

**Issue by serenity4** [JuliaIO/FFMPEG.jl#53]
Using Plots.jl, I get this error when saving a GIF to a file:
```julia-repl
julia> using Plots

julia> @gif for i in 1:1
         heatmap(rand(100, 100))
       end
/home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/ffmpeg: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Transform
ERROR: failed process: Process(`/home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/ffmpeg -v 16 -i /tmp/jl_Yq3vHj/%06d.png -vf palettegen=stats_mode=full -y /tmp/jl_Yq3vHj/palette.bmp`, ProcessExited(127)) [127]
```

It seems like FFMPEG uses my system libharfbuzz, and fails because libharfbuzz expects a symbol to be defined in the FreeType2 library. Looking at the [BinaryBuilder recipe](https://github.com/JuliaPackaging/Yggdrasil/blob/master/F/FFMPEG/FFMPEG/build_tarballs.jl), FreeType2 is listed as a dependency, but not libharfbuzz. 

This was using Plots 1.38.10 with FFMPEG 0.4.1. The version of the harfbuzz installed on my system (Manjaro linux) is 7.1.0.

`ldd` shows

```
$ ldd /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/ffmpeg
        linux-vdso.so.1 (0x00007ffd5dbfc000)
        libavdevice.so.58 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavdevice.so.58 (0x00007f092cb95000)
        libavfilter.so.7 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavfilter.so.7 (0x00007f092c600000)
        libavformat.so.58 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavformat.so.58 (0x00007f092c200000)
        libavcodec.so.58 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavcodec.so.58 (0x00007f092aa00000)
        libavresample.so.4 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavresample.so.4 (0x00007f092cb73000)
        libpostproc.so.55 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libpostproc.so.55 (0x00007f092cb52000)
        libswresample.so.3 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libswresample.so.3 (0x00007f092cb33000)
        libswscale.so.5 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libswscale.so.5 (0x00007f092ca9e000)
        libavutil.so.56 => /home/belmant/.julia/artifacts/b409c0eafb4254a980f9e730f6fbe56867890f6a/bin/../lib/libavutil.so.56 (0x00007f092a600000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f092c518000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f092ca58000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f092a419000)
        libass.so.9 => /usr/lib/libass.so.9 (0x00007f092ca20000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f092c123000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f092c505000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f092c4eb000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f092c08e000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f092a000000)
        libiconv.so.2 => not found
        libiconv.so.2 => not found
        libaom.so.3 => /usr/lib/libaom.so.3 (0x00007f0929600000)
        libfdk-aac.so.2 => /usr/lib/libfdk-aac.so.2 (0x00007f0929eb5000)
        libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007f092c473000)
        libopus.so.0 => /usr/lib/libopus.so.0 (0x00007f092a9a6000)
        libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007f092c060000)
        libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007f092a8fb000)
        libx264.so.163 => not found
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f092ca17000)
        libx265.so.199 => /usr/lib/libx265.so.199 (0x00007f0928200000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f092c05b000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f092cba8000)
        libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f092a8db000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f092a31e000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f09295b1000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f092a2e5000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f092c04d000)
        libogg.so.0 => /usr/lib/libogg.so.0 (0x00007f092c042000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f0927e00000)
        libmvec.so.1 => /usr/lib/libmvec.so.1 (0x00007f0928107000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f0927cb5000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f0929e92000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f0929586000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f0929563000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f092a8bb000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007f092806c000)

$ ldd /usr/lib/libharfbuzz.so 
        linux-vdso.so.1 (0x00007ffc6ae5d000)
        /usr/lib/libstdc++.so.6 (0x00007f996ea00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f996e918000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f996e83b000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f996e6f0000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f996ec9f000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f996e509000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f996edfe000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f996ec7d000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f996ec63000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f996ec50000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f996e4d0000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f996ec42000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007f996e435000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f996e412000)
```

and the version of my system FreeType2 is 2.13.0.

Troubleshooting on the internet revealed that such errors have happened in the past where the FreeType2 library was too old or an unsupported fork, but my FreeType2 and HarfBuzz system packages are the latest from the official Arch repositories.

I don't really have a clue as to why this is happening. I searched for related issues on Plots.jl, [HarfBuzz](https://github.com/harfbuzz/harfbuzz) and [FreeType2](https://gitlab.freedesktop.org/freetype/freetype), but couldn't find anything. Any help would be greatly appreciated!

**Comment by serenity4** [comment]
Apparently, `FT_Get_Transform` has been introduced in FreeType2 2.11, and the latest FreeType2_jll (used by FFMPEG_jll) only has version 2.10.4. The issue comes from FFMPEG_jll using the system HarfBuzz which in turn calls into the FreeType2 library which is picked up to be the old JLL version, and not the system library.

**Comment by giordano** [comment]
The problem is that you're using system libraries _instead_ of jlls. Why that happens, I don't know because I don't how ffmpeg is called, in any case `ldd` is the wrong tool to use to check the status.

**Comment by serenity4** [comment]
From my understanding, that is because HarfBuzz is not listed as a dependency of FFMPEG_jll, which is why `ffmpeg` defaults to using a system lib. I see there is a HarfBuzz_jll, would it be as simple as adding it to the dependencies of FFMPEG_jll to make `ffmpeg` pick up HarfBuzz from the JLL?

**Comment by giordano** [comment]
Again, `ldd` is the completely wrong tool to use here, it's going to show you all system libraries because it has no idea how you're calling ffmpeg from Julia, it can't possibly give you a meaningful output (besides the fact ldd is terrible on its own).

**Comment by serenity4** [comment]
My conclusions do not rely on the output of `ldd`. `ldd` did not give me anything meaningful, for the reasons you mention.

There is the clear issue that `ffmpeg` uses the system `libharfbuzz` as hinted by the error message (see the absolute path):
```
ffmpeg: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Transform
```

I have FreeType2 2.13 installed as system lib, which will not have this undefined symbol error (because the symbol in question was added in FreeType 2.11), therefore I am assuming that it is using the FreeType2 library from the JLL (which, I understand, gets loaded at `__init__` time, bypassing system libraries).

My short-term solution to fix that was to upgrade the FreeType2 JLL to the latest version, which more or less matches the system FreeType2 (which works). A good fix would be however to include HarfBuzz_jll as a `Dependency` to `FFMPEG_jll` such that we can load a compatible `libharfbuzz` at `__init__` without relying on system libs.

**Comment by giordano** [comment]
I'm missing how harfbuzz is relevant here if ffmpeg doesn't depend on it to start with

**Comment by giordano** [comment]
Actually, harfbuzz is an indirect dependency: https://juliahub.com/ui/Packages/FFMPEG_jll/uSD0T?page=1. But this doesn't answer how you're loading system libraries. What's the full output of versioninfo?

**Comment by serenity4** [comment]
Hmm, you are right, it seems like HarfBuzz is indeed loaded.

I found the culprit, my `versioninfo()` was
```julia
julia> versioninfo()
Julia Version 1.10.0-DEV.1583
Commit 5c070f4ac3e (2023-06-28 05:29 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, alderlake)
  Threads: 1 on 20 virtual cores
Environment:
  LD_PRELOAD = /usr/lib/libstdc++.so.6
  JULIA_INFO_COLOR = green
```

Which made me realize I had `LD_PRELOAD = /usr/lib/libstdc++.so.6` (required to work with a GPU driver tool for other stuff). Removing `LD_PRELOAD` does fix the issue. Would you know why which lib is loaded has been affected by loading a specific `libstdc++`?

**Comment by giordano** [comment]
Probably because you're forcing external C++ libraries to be dragged in.
